// ── LISTINGS DATA ──────────────────────────────────────────────────────────
// This is the single source of truth for all property listings.
// Both obiavi.html and index.html use this file.
//
// TO ADD A NEW LISTING: copy an existing entry, increment the id,
// fill in the details, and save. It will automatically appear on both pages.
// ───────────────────────────────────────────────────────────────────────────

const LISTINGS = [
  {
    id: 1,
    deal: 'rent',
    city: 'plovdiv',
    cityLabel: 'Пловдив',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '380',
    priceUnit: '€ / месец',
    priceRaw: 380,
    size: 50,
    isNew: true,
    featured: false,
    title: 'Под наем! Нов, напълно обзаведен!',
    location: '📍 Западен, Пловдив',
    img: 'https://github.com/gericodes/mywebsite/blob/main/1/1.jpg?raw=true',
    feats: ['🛏 1 стая', '🚿 1 баня', '📐 50 м²', '🅿️ възможност за наемане'],
    href: 'listing.html?id=1'
  },
  {
    id: 2,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '70 000',
    priceUnit: '€',
    priceRaw: 70000,
    size: 72,
    isNew: false,
    featured: false,
    title: 'двустаен и магазин',
    location: '📍 Асеновград',
    img: 'https://github.com/gericodes/mywebsite/blob/main/2/1.jpg?raw=true',
    feats: ['🛏 3 стаи', '📐 72 м²', '🏢 Етаж 1/3', '🧱 Стара тухла'],
    href: 'listing.html?id=2'
  },
  {
    id: 3,
    deal: 'sell',
    city: 'drugi',
    cityLabel: 'с. Нови извор',
    type: 'house',
    typeLabel: '🏡 Къща',
    price: '149 000',
    priceUnit: '€',
    priceRaw: 149000,
    size: 190,
    isNew: false,
    featured: true,
    title: 'Къща в с.Нови извор, Пловдив',
    location: '📍 с.Нови извор, Пловдив',
    img: 'https://github.com/gericodes/mywebsite/blob/main/3/1.jpg?raw=true',
    feats: ['🛏 3 стаи', '🚿 1 баня', '📐 190 м²', '🌳 Двор'],
    href: 'listing.html?id=3'
  },
  {
    id: 4,
    deal: 'rent',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '450',
    priceUnit: '€ / месец',
    priceRaw: 450,
    size: 70,
    isNew: true,
    featured: false,
    title: 'Под наем! Нов, напълно обзаведен!',
    location: '📍 Асеновград',
    img: 'https://github.com/gericodes/mywebsite/blob/main/4/1.jpg?raw=true',
    feats: ['🛏 2 стаи', '📐 70 м²'],
    href: 'listing.html?id=4'
  },
  {
    id: 5,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '117 000',
    priceUnit: '€',
    priceRaw: 117000,
    size: 84,
    isNew: false,
    featured: false,
    title: 'Нов тристаен апартамент',
    location: '📍 Асеновград',
    img: 'https://github.com/gericodes/mywebsite/blob/main/5/1.jpg?raw=true',
    feats: ['🛏 3 стаи', '📐 84 м²'],
    href: 'listing.html?id=5'
  },
  {
    id: 6,
    deal: 'sell',
    city: 'drugi',
    cityLabel: 'Белащица',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '81 060',
    priceUnit: '€',
    priceRaw: 81060,
    size: 68,
    isNew: false,
    featured: false,
    title: 'Апартамент в Белащица',
    location: '📍 с. Белащица, Родопи',
    img: 'https://github.com/gericodes/mywebsite/blob/main/6/1.jpg?raw=true',
    feats: ['🛏 2 стаи', '📐 68 м²'],
    href: 'listing.html?id=6'
  },
  {
    id: 9,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '73 132',
    priceUnit: '€',
    priceRaw: 73132,
    size: 70,
    isNew: true,
    featured: false,
    title: 'Продажба 2-стаен гр. Асеновград 70m²',
    location: '📍 кв. Запад, Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1772044/1772044-0.jpg',
    feats: ['🛏 2 стаи', '📐 70 м²', '🏗 В строеж'],
    href: 'listing.html?id=9'
  },
  {
    id: 10,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '73 000',
    priceUnit: '€',
    priceRaw: 73000,
    size: 73,
    isNew: true,
    featured: false,
    title: 'Продажба 2-стаен гр. Асеновград 73m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1772043/1772043-0.jpg',
    feats: ['🛏 2 стаи', '📐 73 м²', '🏗 В строеж'],
    href: 'listing.html?id=10'
  },
  {
    id: 11,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '120 000',
    priceUnit: '€',
    priceRaw: 120000,
    size: 111,
    isNew: true,
    featured: false,
    title: 'Продажба 3-стаен гр. Асеновград 111m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1772042/1772042-0.jpg',
    feats: ['🛏 3 стаи', '📐 111 м²', '🏗 В строеж'],
    href: 'listing.html?id=11'
  },
  {
    id: 12,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '65 340',
    priceUnit: '€',
    priceRaw: 65340,
    size: 66,
    isNew: true,
    featured: false,
    title: 'Продажба 2-стаен гр. Асеновград 66m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1772041/1772041-0.jpg',
    feats: ['🛏 2 стаи', '📐 66 м²', '🏗 В строеж'],
    href: 'listing.html?id=12'
  },
  {
    id: 13,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '92 070',
    priceUnit: '€',
    priceRaw: 92070,
    size: 93,
    isNew: false,
    featured: false,
    title: 'Продажба 3-стаен гр. Асеновград 93m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1772040/a9e5d00e6799db8ebb7d8e631f514965-130526120129.jpg',
    feats: ['🛏 3 стаи', '📐 93 м²'],
    href: 'listing.html?id=13'
  },
  {
    id: 14,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '110 000',
    priceUnit: '€',
    priceRaw: 110000,
    size: 100,
    isNew: false,
    featured: false,
    title: 'Продажба 3-стаен гр. Асеновград 100m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1772039/1772039-0.jpg',
    feats: ['🛏 3 стаи', '📐 100 м²'],
    href: 'listing.html?id=14'
  },
  {
    id: 15,
    deal: 'sell',
    city: 'drugi',
    cityLabel: 'с. Катуница',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '31 642',
    priceUnit: '€',
    priceRaw: 31642,
    size: 0,
    isNew: false,
    featured: false,
    title: 'Имот до с.Катуница',
    location: '📍 с. Катуница, Садово',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1762688/00791c274443d9e4d730b8376ce08c1f-170226022052.jpg',
    feats: ['🌍 Земя за инвестиция'],
    href: 'listing.html?id=15'
  },
  {
    id: 16,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '80 000',
    priceUnit: '€',
    priceRaw: 80000,
    size: 80,
    isNew: false,
    featured: false,
    title: 'Компактен тристаен апартамент',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1686583/b73ed731c3014666603bca8a1032d868-111125022355.jpg',
    feats: ['🛏 3 стаи', '📐 80 м²'],
    href: 'listing.html?id=16'
  },
  {
    id: 17,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '90 000',
    priceUnit: '€',
    priceRaw: 90000,
    size: 90,
    isNew: false,
    featured: false,
    title: 'Продажба 3-стаен гр. Асеновград 90m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1670542/1670542-0.jpg',
    feats: ['🛏 3 стаи', '📐 90 м²'],
    href: 'listing.html?id=17'
  },
  {
    id: 18,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '84 700',
    priceUnit: '€',
    priceRaw: 84700,
    size: 71,
    isNew: false,
    featured: false,
    title: 'Продажба 2-стаен гр. Асеновград 71m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1670527/1670527-0.jpg',
    feats: ['🛏 2 стаи', '📐 71 м²'],
    href: 'listing.html?id=18'
  },
  {
    id: 19,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '73 700',
    priceUnit: '€',
    priceRaw: 73700,
    size: 1440,
    isNew: false,
    featured: false,
    title: 'Продажба Парцел гр. Асеновград 1440m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1670510/1670510-0.jpg',
    feats: ['🌍 Парцел 1440 м²'],
    href: 'listing.html?id=19'
  },
  {
    id: 20,
    deal: 'sell',
    city: 'drugi',
    cityLabel: 'с. Крушово',
    type: 'house',
    typeLabel: '🏡 Къща',
    price: '39 900',
    priceUnit: '€',
    priceRaw: 39900,
    size: 189,
    isNew: false,
    featured: false,
    title: 'Продажба Къща гр. Лъки - с. Крушово 189m²',
    location: '📍 с. Крушово, гр. Лъки',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1504542/efe6fd0d45030e5b2e4dfbd29c89356c-250925093046.jpg',
    feats: ['🏡 Къща', '📐 189 м²'],
    href: 'listing.html?id=20'
  },
  {
    id: 21,
    deal: 'sell',
    city: 'drugi',
    cityLabel: 'с. Павелско',
    type: 'house',
    typeLabel: '🏡 Къща',
    price: '409 000',
    priceUnit: '€',
    priceRaw: 409000,
    size: 460,
    isNew: false,
    featured: false,
    title: 'Продажба Къща гр. Чепеларе - с. Павелско 460m²',
    location: '📍 с. Павелско, Чепеларе',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1504016/1aff6781537c26d4c699992f8f3e8bc2-240925031059.jpg',
    feats: ['🛏 8 стаи', '📐 460 м²'],
    href: 'listing.html?id=21'
  },
  {
    id: 22,
    deal: 'sell',
    city: 'drugi',
    cityLabel: 'гр. Куклен',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '45 000',
    priceUnit: '€',
    priceRaw: 45000,
    size: 0,
    isNew: false,
    featured: false,
    title: 'Земя подходяща за производство',
    location: '📍 гр. Куклен, Пловдив',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1494961/8357849d2b196aceb61de77e21e71404-050925024606.jpg',
    feats: ['🌍 Земя за производство'],
    href: 'listing.html?id=22'
  },
  {
    id: 23,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '126 000',
    priceUnit: '€',
    priceRaw: 126000,
    size: 0,
    isNew: false,
    featured: false,
    title: 'Земя подходяща за промяна на статут',
    location: '📍 кв. Долни Воден, Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1494960/f16d4925cf1dce0c536d5e0442825413-050925024033.jpg',
    feats: ['🌍 Земя за промяна на статут'],
    href: 'listing.html?id=23'
  },
  {
    id: 24,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'house',
    typeLabel: '🏡 Къща',
    price: '175 000',
    priceUnit: '€',
    priceRaw: 175000,
    size: 0,
    isNew: false,
    featured: false,
    title: 'Масивна къща в Долнослав',
    location: '📍 с. Долнослав, Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1492474/19332976769de3c6aaf433703051b643-030925104221.jpg',
    feats: ['🛏 5 стаи', '🏡 Масивна къща'],
    href: 'listing.html?id=24'
  },
  {
    id: 25,
    deal: 'sell',
    city: 'drugi',
    cityLabel: 'с. Милево',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '110 000',
    priceUnit: '€',
    priceRaw: 110000,
    size: 0,
    isNew: false,
    featured: false,
    title: 'Имот с голям потенциал на брега на река Марица',
    location: '📍 с. Милево, Садово',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1488790/a90de9f70f7530e55ddefdd10d930e92-270825104030.jpg',
    feats: ['🌍 Земя за инвестиция', '💧 Бряг на Марица'],
    href: 'listing.html?id=25'
  },
  {
    id: 26,
    deal: 'rent',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'commercial',
    typeLabel: '🏪 Бизнес имот',
    price: '900',
    priceUnit: '€ / месец',
    priceRaw: 900,
    size: 0,
    isNew: false,
    featured: false,
    title: 'Магазин / Склад',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1487640/1db71787e88d6e66f68429ab68b75773-240825020352.jpg',
    feats: ['🏪 Магазин / Склад'],
    href: 'listing.html?id=26'
  },
  {
    id: 27,
    deal: 'sell',
    city: 'plovdiv',
    cityLabel: 'Пловдив',
    type: 'house',
    typeLabel: '🏡 Къща',
    price: '325 000',
    priceUnit: '€',
    priceRaw: 325000,
    size: 500,
    isNew: false,
    featured: false,
    title: 'Продажба Къща гр. Пловдив - Коматево 500m²',
    location: '📍 Коматево, Пловдив',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1485165/8009be404bef1a88d2049e189453b6b5-180925125026.jpg',
    feats: ['🛏 4 стаи', '📐 500 м²'],
    href: 'listing.html?id=27'
  },
  {
    id: 28,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '93 100',
    priceUnit: '€',
    priceRaw: 93100,
    size: 98,
    isNew: false,
    featured: false,
    title: 'Ново строителство двустаен апартамент с голяма тераса',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1464393/474e80dcfee32f538080f50f1946b651-220725014038.jpg',
    feats: ['🛏 3 стаи', '📐 98 м²', '🌿 Голяма тераса'],
    href: 'listing.html?id=28'
  },
  {
    id: 29,
    deal: 'sell',
    city: 'drugi',
    cityLabel: 'Белащица',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '141 000',
    priceUnit: '€',
    priceRaw: 141000,
    size: 118,
    isNew: false,
    featured: false,
    title: 'Продажба 3-стаен с. Белащица',
    location: '📍 с. Белащица, Родопи',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1452324/f4db6480bca3c15af587be55a75e72d0-200825013414.jpg',
    feats: ['🛏 3 стаи', '📐 118 м²'],
    href: 'listing.html?id=29'
  },
  {
    id: 30,
    deal: 'rent',
    city: 'plovdiv',
    cityLabel: 'Пловдив',
    type: 'commercial',
    typeLabel: '🅿️ Гараж',
    price: '80',
    priceUnit: '€ / месец',
    priceRaw: 80,
    size: 20,
    isNew: false,
    featured: false,
    title: 'Дава под наем гр. Пловдив 20m² (гараж)',
    location: '📍 Пловдив',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1450266/1450266-0.jpg',
    feats: ['🅿️ Гараж / Паркомясто', '📐 20 м²'],
    href: 'listing.html?id=30'
  },
  {
    id: 31,
    deal: 'rent',
    city: 'plovdiv',
    cityLabel: 'Пловдив',
    type: 'commercial',
    typeLabel: '🅿️ Гараж',
    price: '51',
    priceUnit: '€ / месец',
    priceRaw: 51,
    size: 20,
    isNew: false,
    featured: false,
    title: 'Дава под наем гр. Пловдив 20m² (2)',
    location: '📍 Пловдив',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1450264/1450264-0.jpg',
    feats: ['🅿️ Гараж / Паркомясто', '📐 20 м²'],
    href: 'listing.html?id=31'
  },
  {
    id: 32,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '114 000',
    priceUnit: '€',
    priceRaw: 114000,
    size: 120,
    isNew: false,
    featured: false,
    title: 'Продажба 3-стаен гр. Асеновград 110m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1450262/d7312fa178654291e9337134decc7c34-220725010544.jpg',
    feats: ['🛏 3 стаи', '📐 120 м²'],
    href: 'listing.html?id=32'
  },
  {
    id: 33,
    deal: 'sell',
    city: 'drugi',
    cityLabel: 'Белащица',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '88 680',
    priceUnit: '€',
    priceRaw: 88680,
    size: 74,
    isNew: false,
    featured: false,
    title: 'Продажба 2-стаен с. Белащица',
    location: '📍 с. Белащица, Родопи',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1450258/8d53b1291c95ce3fdfcdd78320780798-180925125734.jpg',
    feats: ['🛏 2 стаи', '📐 74 м²'],
    href: 'listing.html?id=33'
  },
  {
    id: 34,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'house',
    typeLabel: '🏡 Къща',
    price: '120 000',
    priceUnit: '€',
    priceRaw: 120000,
    size: 162,
    isNew: false,
    featured: false,
    title: 'Продажба Етаж от къща гр. Асеновград 162m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1450255/1450255-0.jpg',
    feats: ['🏡 Етаж от къща', '📐 162 м²'],
    href: 'listing.html?id=34'
  },
  {
    id: 35,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '47 857',
    priceUnit: '€',
    priceRaw: 47857,
    size: 1560,
    isNew: false,
    featured: false,
    title: 'Продажба Парцел гр. Асеновград 1560m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1450251/d93c9cb2a810a639ba43c8c252209068-220725124434.jpg',
    feats: ['🌍 Парцел 1560 м²'],
    href: 'listing.html?id=35'
  },
  {
    id: 36,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '67 491',
    priceUnit: '€',
    priceRaw: 67491,
    size: 2187,
    isNew: false,
    featured: false,
    title: 'Продажба Парцел гр. Асеновград 2187m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1450248/1450248-0.jpg',
    feats: ['🌍 Парцел 2187 м²'],
    href: 'listing.html?id=36'
  },
  {
    id: 37,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '3 068',
    priceUnit: '€',
    priceRaw: 3068,
    size: 1152,
    isNew: false,
    featured: false,
    title: 'Продажба Земеделска земя гр. Асеновград 1152m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1450245/1450245-0.jpg',
    feats: ['🌍 Земеделска земя 1152 м²'],
    href: 'listing.html?id=37'
  },
  {
    id: 38,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '55 000',
    priceUnit: '€',
    priceRaw: 55000,
    size: 992,
    isNew: false,
    featured: false,
    title: 'Продажба Парцел гр. Асеновград 992m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1450246/1450246-0.jpg',
    feats: ['🌍 Парцел 992 м²'],
    href: 'listing.html?id=38'
  },
  {
    id: 39,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'apartment',
    typeLabel: '🏢 Апартамент',
    price: '136 000',
    priceUnit: '€',
    priceRaw: 136000,
    size: 118,
    isNew: false,
    featured: false,
    title: 'Продажба 3-стаен гр. Асеновград 118m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1450237/639198c8eda03a98541702c0c32dad1c-150725014007.jpg',
    feats: ['🛏 3 стаи', '📐 118 м²'],
    href: 'listing.html?id=39'
  },
  {
    id: 40,
    deal: 'sell',
    city: 'drugi',
    cityLabel: 'Нареченски бани',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '20 452',
    priceUnit: '€',
    priceRaw: 20452,
    size: 327,
    isNew: false,
    featured: false,
    title: 'Продажба Парцел с. Нареченски бани 327m²',
    location: '📍 с. Нареченски бани, Родопи',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1450234/1450234-0.jpg',
    feats: ['🌍 Парцел 327 м²'],
    href: 'listing.html?id=40'
  },
  {
    id: 41,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '12 782',
    priceUnit: '€',
    priceRaw: 12782,
    size: 1319,
    isNew: false,
    featured: false,
    title: 'Продажба Парцел гр. Асеновград 1319m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1450235/1450235-0.jpg',
    feats: ['🌍 Парцел 1319 м²'],
    href: 'listing.html?id=41'
  },
  {
    id: 42,
    deal: 'sell',
    city: 'drugi',
    cityLabel: 'с. Милево',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '102 000',
    priceUnit: '€',
    priceRaw: 102000,
    size: 4071,
    isNew: false,
    featured: false,
    title: 'Продажба Парцел с. Милево 4071m²',
    location: '📍 с. Милево, Родопи',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1450232/1450232-0.jpg',
    feats: ['🌍 Парцел 4071 м²'],
    href: 'listing.html?id=42'
  },
  {
    id: 43,
    deal: 'sell',
    city: 'drugi',
    cityLabel: 'с. Поройна',
    type: 'house',
    typeLabel: '🏡 Къща',
    price: '75 000',
    priceUnit: '€',
    priceRaw: 75000,
    size: 130,
    isNew: false,
    featured: false,
    title: 'Продажба Къща с. Поройна 130m²',
    location: '📍 с. Поройна, Родопи',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1442649/1442649-0.jpg',
    feats: ['🏡 Къща', '📐 130 м²'],
    href: 'listing.html?id=43'
  },
  {
    id: 44,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'house',
    typeLabel: '🏡 Къща',
    price: '51 000',
    priceUnit: '€',
    priceRaw: 51000,
    size: 64,
    isNew: false,
    featured: false,
    title: 'Продажба Къща гр. Асеновград 64m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1440032/1440032-0.jpg',
    feats: ['🏡 Къща', '📐 64 м²'],
    href: 'listing.html?id=44'
  },
  {
    id: 45,
    deal: 'sell',
    city: 'drugi',
    cityLabel: 'с. Руен',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '15 000',
    priceUnit: '€',
    priceRaw: 15000,
    size: 760,
    isNew: false,
    featured: false,
    title: 'Продажба Парцел с. Руен 760m²',
    location: '📍 с. Руен, Родопи',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1440031/1440031-0.jpg',
    feats: ['🌍 Парцел 760 м²'],
    href: 'listing.html?id=45'
  },
  {
    id: 46,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '25 565',
    priceUnit: '€',
    priceRaw: 25565,
    size: 980,
    isNew: false,
    featured: false,
    title: 'Продажба Парцел с. Конуш 980m²',
    location: '📍 с. Конуш, Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1440026/1440026-0.jpg',
    feats: ['🌍 Парцел 980 м²'],
    href: 'listing.html?id=46'
  },
  {
    id: 47,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '25 000',
    priceUnit: '€',
    priceRaw: 25000,
    size: 887,
    isNew: false,
    featured: false,
    title: 'Продажба Парцел с. Сини връх 887m²',
    location: '📍 с. Сини връх, Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1440025/1440025-0.jpg',
    feats: ['🌍 Парцел 887 м²'],
    href: 'listing.html?id=47'
  },
  {
    id: 48,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '92 033',
    priceUnit: '€',
    priceRaw: 92033,
    size: 1800,
    isNew: false,
    featured: false,
    title: 'Продажба Парцел гр. Асеновград 1800m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1440021/1440021-0.jpg',
    feats: ['🌍 Парцел 1800 м²'],
    href: 'listing.html?id=48'
  },
  {
    id: 49,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '226 870',
    priceUnit: '€',
    priceRaw: 226870,
    size: 3241,
    isNew: false,
    featured: false,
    title: 'Продажба Парцел гр. Асеновград 3241m²',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1440018/1440018-0.jpg',
    feats: ['🌍 Парцел 3241 м²'],
    href: 'listing.html?id=49'
  },
  {
    id: 50,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'parcel',
    typeLabel: '🌍 Парцел',
    price: '69 024',
    priceUnit: '€',
    priceRaw: 69024,
    size: 9000,
    isNew: false,
    featured: false,
    title: 'Продажба Парцел гр. Асеновград 9000m²',
    location: '📍 с. Мулдава, Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1440014/1440014-0.jpg',
    feats: ['🌍 Парцел 9000 м²'],
    href: 'listing.html?id=50'
  },
  {
    id: 51,
    deal: 'sell',
    city: 'asenovgrad',
    cityLabel: 'Асеновград',
    type: 'commercial',
    typeLabel: '🏭 Бизнес имот',
    price: '580 000',
    priceUnit: '€',
    priceRaw: 580000,
    size: 0,
    isNew: false,
    featured: false,
    title: 'Цех за мебели в гр. Асеновград',
    location: '📍 Асеновград',
    img: 'https://realestatepoint.estateplus.net/storage/photos/modified/1200x/realestatepoint_298/offers/1425270/6001f6cab565a5ea071cdeed3cbc6319-030725124227.jpg',
    feats: ['🏭 Производствен цех'],
    href: 'listing.html?id=51'
  }
];

// Builds a card element from a listing object.
// mode: 'index' (simpler, click whole card) | 'obiavi' (with footer, filters)
function buildListingCard(listing, mode) {
  const dealLabel = listing.deal === 'rent' ? 'Под наем' : 'Продажба';
  const dealClass = listing.deal === 'rent' ? 'badge-rent' : 'badge-sell';
  const newBadge = listing.isNew ? '<span class="badge-new">Ново</span>' : '';
  const featsHtml = listing.feats.map(f => `<span class="feat">${f}</span>`).join('');

  const card = document.createElement('div');
  card.id = `listing-card-${listing.id}`;
  card.className = 'listing-card';
  card.dataset.deal = listing.deal;
  card.dataset.city = listing.city;
  card.dataset.type = listing.type;
  card.dataset.price = listing.priceRaw;
  card.dataset.size = listing.size;
  card.dataset.newest = listing.id;
  card.dataset.featured = listing.featured ? 'true' : 'false';

  card.innerHTML = `
    <div class="card-img" style="background-image:url('${listing.img}')">
      <div class="card-img-overlay"></div>
      <span class="card-type-badge ${dealClass}">${dealLabel}</span>
      ${newBadge}
    </div>
    <div class="card-body">
      <div class="card-top">
        <div>
          <div class="card-price">${listing.price} <span class="card-price-unit">${listing.priceUnit}</span></div>
        </div>
        <span class="card-city-tag">${listing.cityLabel}</span>
      </div>
      <div class="card-title">${listing.title}</div>
      <div class="card-location">${listing.location}</div>
      <div class="card-features">${featsHtml}</div>
    </div>
    <div class="card-footer">
      <span class="card-prop-type">${listing.typeLabel}</span>
      <a href="${listing.href}" class="card-cta">Детайли →</a>
    </div>`;

  card.style.cursor = 'pointer';
  card.addEventListener('click', e => {
    if (!e.target.closest('a')) window.location.href = listing.href;
  });

  return card;
}
